import turtle
wn = turtle.Screen()
turtle.bgcolor("blue")
turtle.color("yellow")

picasso = turtle.Turtle()

picasso.forward(75)
picasso.left(90)
picasso.forward(25)
picasso.left(90)
picasso.forward(10)
picasso.right(90)
picasso.forward(125)
picasso.right(135)
picasso.forward(100)
picasso.left(90)
picasso.forward(100)
picasso.right(135)
picasso.forward(125)
picasso.right(90)
picasso.forward(10)
picasso.left(90)
picasso.forward(25)
picasso.left(90)
picasso.forward(75)
picasso.left(90)
picasso.forward(25)
picasso.left(90)
picasso.forward(10)
picasso.right(90)
picasso.forward(215)
picasso.left(135)
picasso.forward(175)
picasso.right(90)
picasso.forward(175)
picasso.left(135)
picasso.forward(215)
picasso.right(90)
picasso.forward(15)
picasso.left(90)
picasso.forward(25)
turtle.mainloop()
